# Generated by Django 4.2.2 on 2023-06-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_new_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='image',
        ),
    ]
